import type { NextPage } from "next";
import Head from "next/head";
import { Banner } from "../components/Banner";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Festicar</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className="relative">
          <Banner />
        </div>
      </main>
    </div>
  );
};

export default Home;
